# These are supported funding model platforms

github: ToastHawaii
custom:
  [
    "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=JFWXTYPKBD2YA&source=url",
    "https://brave.com/brave-rewards/",
  ]
