defaults:
  - scope:
      path: "docs/README.md"
    values:
      lang: "en"
      title: "Priceless"
      description: "Experience the world. Free of charge."
      base: "/"
      tagline: "Priceless map"
  - scope:
      path: "de/docs/README.md"
    values:
      lang: "de"
      title: "Unbezahlbar"
      description: "Erlebe die Welt. Gratis."
      base: "/de/"
      tagline: "Unbezahlbar Karte"
