// Copyright (C) 2020 Markus Peloso
//
// This file is part of Priceless map.
//
// Priceless map is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// Priceless map is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with Priceless map.  If not, see <http://www.gnu.org/licenses/>.

import { type } from "./local.type";

export const local = {
  code: "de",
  title: "Unbezahlbar Karte",
  description: "Erlebe die Welt. Gratis.",
  minZoomMessageNoLayer: "Keine Ebene zugewiesen",
  minZoomMessage: "Zoome hinein, um Kartenmerkmale zu laden",
  emptyIndicator: "Keine Kartenobjekte in diesem Bereich gefunden",
  linkCopied: "Link in die Zwischenablage kopiert",
  capacity: "Kapazität",
  playground: "Für Kinder",
  changing_table: "Hat einen Wickeltisch",
  bottle: "Nachfüllen ist möglich",
  pump: "Pumpe",
  tools: "Werkzeuge",
  repair: "Reparieren",
  chainTool: "Kettennietdrücker",
  internet: "Internet",
  water: "Trinkwasser",
  bicycle: "Velo",
  park: "Park",
  charging: "Aufladen",
  mobileCharging: "Aufladen",
  car: "Auto",
  mobile: "Smartphone",
  smallElectronics: "Kleine Elektrongeräte",
  electronics: "Elektrongeräte",
  furniture: "Möbel",
  computer: "Computer",
  defibrillator: "Defibrillator",
  toy: "Spielzeug",
  clothes: "Kleider",
  battery: "Batterie",
  carBattery: "Autobatterie",
  cookingOil: "Speiseöl",
  engineOil: "Maschinenöl",
  oil: "Altöl",
  paint: "Farbe",
  rubble: "Steingut",
  plastic: "Plastik",
  plastic_bottles: "Plastikflaschen",
  plastic_packaging: "Plastikverpackung",
  PET: "PET",
  plastic_bags: "Plastiktasche",
  polyester: "Polyester",
  polystyrene_foam: "Styropor",
  hazardous: "Sondermüll",
  hydrargyrum: "Quecksilber",
  shoes: "Schuhe",
  recycling: "Weiterverwerten",
  reuse: "Wiederverwenden",
  freeToGive: "Nur bringen",
  freeToTake: "Nur mitnehmen",
  freeToTakeOrGive: "Mitnehmen und bringen",
  borrow: "Nur ausleihen",
  indoor: "Drinnen",
  female: "Für Frauen",
  male: "Für Männer",
  senior: "Für Ältere",
  disabled: "Für Behinderte",
  homeless: "Für Benachteiligte",
  migrant: "Für Vertriebene",
  lgbtq: "LGBTQ+ freundlich",
  hoops: "Körbe",
  light: "Beleuchtet",
  covered: "Überdacht",
  wheelchair: {
    yes: "Rollstuhlgerecht",
    limited: "Limitiert Rollstuhlgerecht",
    no: "Nicht Rollstuhlgerecht",
  },
  colour: "Farbe",
  open: "Geöffnet",
  closed: "Geschlossen",
  maybeOpen: "Vielleicht geöffnet",
  maybeOpens: "Öffnet vielleicht",
  maybeCloses: "Schliesst vielleicht",
  opens: "Öffnet",
  closes: "Schliesst",
  thatDependsOn: "Das hängt ab von",
  conditionalFee: "Nur zu bestimmten Zeiten kostenlos.",
  horizontalBar: "Reck",
  parallelBars: "Parallelbarren",
  rings: "Ringe",
  exerciseMachine: "Übungsgerät",
  balance: "Gleichgewicht",
  route: "Routen",
  difficulty: "Schwierigkeitsgrad",
  externalResources: "Andere",
  group: {
    culture: "Kultur",
    education: "Bildung",
    natural: "Natur",
    object_of_utility: "Hilfsmittel",
    health: "Gesundheit",
    community: "Gemeinschaft",
    sport: "Sport",
    communitySport: "Gemeinschaftssport",
    trip: "Ausflug",
    goods: "Gegenstände",
    material: "Material weiterverwerten",
  },
  type: type,
};
