// Copyright (C) 2020 Markus Peloso
//
// This file is part of Priceless map.
//
// Priceless map is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// Priceless map is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with Priceless map.  If not, see <http://www.gnu.org/licenses/>.

import { type } from "./local.type";

export const local = {
  code: "",
  title: "Priceless map",
  description: "Experience the world. Free of charge.",
  minZoomMessageNoLayer: "No layer assigned",
  minZoomMessage: "Zoom in to load map features",
  emptyIndicator: "No map features found in this area",
  linkCopied: "Link copied to the clipboard",
  capacity: "Capacity",
  playground: "For children",
  changing_table: "Has a changing table",
  bottle: "Refilling is possible",
  pump: "Pump",
  tools: "Tools",
  repair: "Repair",
  chainTool: "Chain tool",
  internet: "Internet",
  water: "Drinking water",
  bicycle: "Bicycle",
  park: "Park",
  charging: "Charging",
  mobileCharging: "Charging",
  car: "Car",
  mobile: "Mobile phone",
  smallElectronics: "Small Electronics",
  electronics: "Electronics",
  furniture: "Furniture",
  computer: "Computer",
  toy: "Toy",
  clothes: "Clothes",
  battery: "Battery",
  carBattery: "Car battery",
  cookingOil: "Cooking oil",
  engineOil: "Engine oil",
  oil: "Waste oil",
  paint: "Paint",
  rubble: "Building rubble",
  plastic: "Plastic",
  plastic_bottles: "Plastic bottles",
  plastic_packaging: "Plastic packaging",
  PET: "PET",
  plastic_bags: "Plastic bag",
  polyester: "Polyester",
  polystyrene_foam: "Polystyrene foam",
  hazardous: "Hazardous waste",
  hydrargyrum: "Quicksilver",
  shoes: "Shoes",
  recycling: "Recycling",
  reuse: "Reuse",
  freeToGive: "Free to give",
  freeToTake: "Free to take",
  freeToTakeOrGive: "Free to take or give",
  borrow: "Borrow only",
  indoor: "Indoor",
  female: "For women",
  male: "For men",
  senior: "For elderly",
  disabled: "For disabled",
  homeless: "For underprivileged",
  migrant: "For refugees",
  lgbtq: "LGBTQ+ friendly",
  hoops: "Hoops",
  light: "Lit",
  covered: "Covered",
  wheelchair: {
    yes: "Wheelchair accessible",
    limited: "Limited wheelchair accessible",
    no: "Not wheelchair accessible",
  },
  colour: "Color",
  open: "Open",
  closed: "Closed",
  maybeOpen: "Maybe open",
  maybeOpens: "Maybe opens",
  maybeCloses: "Maybe closes",
  opens: "Opens",
  closes: "Closes",
  thatDependsOn: "That depends on",
  conditionalFee: "Only free at certain times.",
  horizontalBar: "Horizontal bar",
  parallelBars: "Parallel bars",
  rings: "Rings",
  exerciseMachine: "Exercise machine",
  balance: "Balance",
  route: "Route",
  difficulty: "Difficulty",
  externalResources: "Others",
  group: {
    culture: "Culture",
    education: "Education",
    natural: "Nature",
    object_of_utility: "Objects of utility",
    health: "Health",
    community: "Community",
    sport: "Sport",
    communitySport: "Community sport",
    trip: "Trip",
    goods: "Goods",
    material: "Material recycling",
  },
  type: type,
};
